apiVersion: v1
kind: PersistentVolume
metadata:
  name: oc-bg-volume
  namespace: oc
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.path }}
  storageClassName: local