apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc-bg-volume-claim
  namespace: oc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
  volumeName: oc-bg-volume