apiVersion: v1
kind: Service
metadata:
  name: {{ include "bl-bg.fullname" . }}
  labels:
    {{- include "bl-bg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 25577
      targetPort: 25577
      nodePort: {{ .Values.service.port }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "bl-bg.selectorLabels" . | nindent 4 }}
