FROM openjdk:17
WORKDIR /usr/src/server
RUN cd .. && mkdir jar && mkdir test && cd jar && curl https://meta.fabricmc.net/v2/versions/loader/1.19.2/0.14.10/0.11.1/server/jar -o fabric.jar && cd /usr/src/server