apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc4-smp-volume-claim
  namespace: oc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      type: local