apiVersion: v1
kind: Service
metadata:
  name: {{ include "oc4-smp.fullname" . }}
  labels:
    {{- include "oc4-smp.labels" . | nindent 4 }}
spec:
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: tcp
  selector:
    {{- include "oc4-smp.selectorLabels" . | nindent 4 }}
