apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bl-cmp-volume-claim
  namespace: bl
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      type: local
  volumeName: bl-cmp-volume