apiVersion: v1
kind: Service
metadata:
  name: {{ include "bl-cmp.fullname" . }}
  labels:
    {{- include "bl-cmp.labels" . | nindent 4 }}
spec:
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: tcp
  selector:
    {{- include "bl-cmp.selectorLabels" . | nindent 4 }}
